#!/bin/bash

read -p " enter num1: " startnum
read -p " enter num2: " endnum

for ((i=$startnum;i<$endnum;i++))
do
flag=0
for ((j=2;j<$i;j++))
do
cond=$(($i%$j))
if [ $cond -eq 0 ]
then
flag=1
break
fi
done
if [ $flag -eq 0 ]
then
echo $i
fi
done
