TASK-01:
CREATE TABLE STUDENT_INFO(
    ID INT(10) PRIMARY KEY,
    NAME VARCHAR(50),
    CGPA FLOAT (10,2),
    SECTION VARCHAR(2),
    COURSE VARCHAR (10)
    );

INSERT INTO STUDENT_INFO (ID,NAME,CGPA,SECTION,COURSE)
VALUES (1,'RATI',3.45,'A','CSE311'),
(2,'AKIB',3.90,'A','CSE312'),
(3,'ESHA',2.95,'B','CSE312'),
(4,'NABIL',3.04,'A','CSE311'),
(5,'BIJOY',3.67,'B','CSE312');

AND OR NOT:
SELECT CGPA FROM STUDENT_INFO
WHERE NAME = 'NABIL' OR ID = 5;

SELECT CGPA FROM STUDENT_INFO
WHERE NAME = 'NABIL' OR ID = 5 OR SECTION = 'A' AND COURSE = 'CSE312';

SELECT CGPA FROM STUDENT_INFO
WHERE NAME = 'NABIL' OR (ID = 5 OR SECTION = 'A') AND COURSE = 'CSE312';

SELECT NAME FROM STUDENT_INFO
WHERE CGPA != 4.00;

DATATYPE
Numeric:
1.	Tiny int (1 byte)
2.	Small int (2 byte)
3.	Int (4 byte)
4.	Bit (1 bit)
5.	Float 
6.	Decimal
String:
1.	Char
2.	Varchar
3.	Text
Other:
1.	Date – time
2.	Date
3.	Time
4.	Year
5.	image
