SELECT NAME, CITY FROM EMPLOYEE_TABLE WHERE SALARY IN (SELECT MAX(SALARY) FROM EMPLOYEE_TABLE);
SELECT * FROM EMPLOYEE_TABLE WHERE EXPERIENCE >=2 AND EXPERIENCE <=7;
SELECT MAX(AGE) FROM EMPLOYEE_TABLE WHERE AGE IN (SELECT AGE WHERE SALARY<4000);
SELECT AGE FROM EMPLOYEE_TABLE WHERE AGE IN (SELECT AVG(SALARY) FROM EMPLOYEE_TABLE);
SELECT * FROM EMPLOYEE_TABLE WHERE EXPERIENCE IN (SELECT MAX(EXPERIENCE) FROM EMPLOYEE_TABLE);
SELECT NAME FROM EMPLOYEE_TABLE WHERE EXPERIENCE IN (SELECT MIN(EXPERIENCE) FROM EMPLOYEE_TABLE WHERE DEPARTMENT IN('CSE'));
SELECT COUNTRY FROM EMPLOYEE_TABLE WHERE AGE IN ((SELECT MAX(AGE) FROM EMPLOYEE_TABLE WHERE DESIGNATION IN('AP')));
SELECT SUM(SALARY) AS 'SALARY_EXPENSE' FROM EMPLOYEE_TABLE WHERE DEPARTMENT = 'ETE';
SELECT MIN(NAME) AS 'MIN_NAME' FROM EMPLOYEE_TABLE;
