1.
CREATE DATABASE RAYHAN;


CREATE TABLE EMPLOYEE_TABLE(
    ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR (50),
    CITY VARCHAR (50),
    COUNTRY VARCHAR (50),
    AGE INT (10),
    SALARY INT (10),
    EXPERIENCE INT (10),
    DEPARTMENT VARCHAR (50),
    DESIGNATION VARCHAR (50)
    );


INSERT INTO EMPLOYEE_TABLE (NAME,CITY,COUNTRY,AGE,SALARY,EXPERIENCE,DEPARTMENT,DESIGNATION)
VALUES ('JANE','BROOKLYN','USA',25,6000,5,'CSE','LECTURER'),
('JACK','LONDON','ENGLAND',32,5000,7,'EEE','AP'),
('PENNY','YALE','CANADA',26,6000,5,'ETE','AP'),
('PAIGE','NEVADA','USA',32,3000,5,'CSE','PROF'),
('MISSY','BROOKLYN','USA',25,3000,5,'CSE','LECTURER'),
('LINDA','YORK','CANADA',24,3000,5,'CSE','AP'),
('LINDA','TOTRONTO','CANADA',26,4000,5,'EEE','AP'),
('MISSY','BERLIN','GERMANY',24,4000,5,'ETE','PROF'),
('PAIGE','HAMBURG','GERMANY',32,6000,5,'ETE','AP'),
('MISSY','BERLIN','GERMANY',41,9000,5,'CSE','PROF');


2. UPDATE employee_table SET SALARY = SALARY+1000 WHERE DESIGNATION ='LECTURER';
3. SELECT NAME,ID FROM employee_table WHERE Country != 'GERMANY' AND AGE<30;

4. 
UPDATE employee_table SET EXPERIENCE = EXPERIENCE-2 WHERE AGE BETWEEN 30 AND 40;
SELECT NAME,EXPERIENCE FROM employee_table WHERE AGE BETWEEN 30 AND 40;

5.
SELECT NAME,AGE,COUNTRY FROM employee_table
WHERE NAME LIKE 'J%' OR '%A' AND DEPARTMENT LIKE '%E%' OR '%E' OR 'E%';
